security:
  oauth2:
    client:
      clientId: 689922584491830
      clientSecret: 6ab7e9bfb4a09f89d4d3c289cac0718d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
